<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BankAccount.Domain\BankAccount.Domain.csproj" />
    <PackageReference Include="SourceFlow.Net" Version="1.0.0" />
  </ItemGroup>

</Project>


